DROP TABLE "MGD"."TENEMENTS" ;
CREATE TABLE "MGD"."TENEMENTS" 

   (	
   "ID" NUMBER(8),
   "TENID" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"OWNER" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"AREA" VARCHAR2(20 BYTE), 
	"APPDATE" VARCHAR2(20 BYTE), 
	"GRANTDATE" VARCHAR2(20 BYTE), 
	"EXPIREDATE" VARCHAR2(20 BYTE), 
	"FILEDATE" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(255 BYTE), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" , 
	"ACTIVITY_CODE" CHAR(1 BYTE), 
	"STATE" VARCHAR2(3 BYTE),
  "RECORDDATE" DATE,
  "ENTRYDATE" DATE,
  CONSTRAINT "TENEMENTS_PK" PRIMARY KEY ("ID")
   )