DROP TABLE "TENEMENTS" ;
CREATE TABLE "TENEMENTS" 

   (	
   "TENEMENTNO" NUMBER(8),
   "NAME" VARCHAR2(50 BYTE), 
	"TENEMENTTYPE" VARCHAR2(50 BYTE), 
	"COMMODITY" VARCHAR2(50 BYTE), 
	"OWNER" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"AREA" VARCHAR2(20 BYTE), 
	"APPLICATIONDATE" DATE, 
	"GRANTDATE" DATE, 
	"EXPIREDATE" DATE, 
	"FILEID" VARCHAR2(50 BYTE), 
	"SOURCE" VARCHAR2(255 BYTE), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" , 
	"ACTIVITY_CODE" CHAR(1 BYTE), 
	"STATE" VARCHAR2(3 BYTE),
  "RECORDDATE" DATE,
  "ENTRYDATE" DATE,
  CONSTRAINT "TENEMENTS_PK" PRIMARY KEY ("TENEMENTNO")
   )